theme: jekyll-theme-minimal
title: Ayoub Fatihi
github: [metadata]
description: Personal web page
# Google Analytics
google_analytics: G-4GHQXMHNEG

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
